# Generated by Django 3.1.5 on 2021-02-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='orders',
            field=models.ManyToManyField(related_name='related_user', to='StoreApp.Purchase', verbose_name='User purchases'),
        ),
    ]
