# Generated by Django 3.2.6 on 2021-08-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0003_alter_product_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('SM', 'Smartphones'), ('LP', 'Laptops'), ('GD', 'Gadgets'), ('AU', 'Audio'), ('PV', 'Photo_Video')], max_length=2),
        ),
    ]
