# Generated by Django 3.2.6 on 2021-08-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0004_alter_category_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('Smartphones', 'Smartphones'), ('Laptops', 'Laptops'), ('Gadgets', 'Gadgets'), ('Audio', 'Audio'), ('Photo_Video', 'Photo_Video')], max_length=25),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
